version: '3'
volumes:
  dados:
networks:
  banco:
  web:
  fila:
services:
  db:
    image: postgres:9.6
    volumes:
      # Volume dos dados
      - dados:/var/lib/postgres/data    
      # Volume para compartilhar script host para o servicos (containers)
      - ./scripts:/scripts
      # Execucao scripts conforme documentacao docker postgres
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - banco
  frontend:
    image: nginx:1.13
    volumes:
      # Site
      - ./web:/usr/share/nginx/html/
      # Mapeamento arquivo de config. do nginx default.conf para o servico
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - web
    depends_on:
      - app
  app:
    image: python:3.6
    volumes:
      # Mapeamento da aplicacao local para o servico
      - ./app:/app
    # diretorio para execucao
    working_dir: /app 
    command: bash ./app.sh
    networks:
      - banco
      - web
      - fila
    depends_on:
      - db
      - queue
    environment:
      - DB_NAME=
      - DB_HOST=
      - DB_USER=
  queue:
    image: redis:3.2
    networks:
      - fila
  worker:
    build: worker
    volumes:
      - ./worker:/worker
    working_dir: /worker
    command: worker.py
    networks:
      - fila
    depends_on:
      - queue
    environment:
      - REDIS_HOST=